#!/bin/sh
RMFILES=(
src/gresource/gnome-shell-dark.css
src/gresource/gnome-shell-high-contrast-dark.css
src/gresource/gnome-shell-high-contrast.css
src/gresource/gnome-shell-theme.gresource
src/gresource/gnome-shell.css
themes/Flat-Remix-Black-Light-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Black-Light/gnome-shell/gnome-shell.css
themes/Flat-Remix-Blue-Dark-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Blue-Dark/gnome-shell/gnome-shell.css
themes/Flat-Remix-Blue-Darkest-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Blue-Darkest/gnome-shell/gnome-shell.css
themes/Flat-Remix-Blue-Light-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Blue-Light/gnome-shell/gnome-shell.css
themes/Flat-Remix-Brown-Dark-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Brown-Dark/gnome-shell/gnome-shell.css
themes/Flat-Remix-Brown-Darkest-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Brown-Darkest/gnome-shell/gnome-shell.css
themes/Flat-Remix-Brown-Light-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Brown-Light/gnome-shell/gnome-shell.css
themes/Flat-Remix-Cyan-Dark-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Cyan-Dark/gnome-shell/gnome-shell.css
themes/Flat-Remix-Cyan-Darkest-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Cyan-Darkest/gnome-shell/gnome-shell.css
themes/Flat-Remix-Cyan-Light-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Cyan-Light/gnome-shell/gnome-shell.css
themes/Flat-Remix-Green-Dark-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Green-Dark/gnome-shell/gnome-shell.css
themes/Flat-Remix-Green-Darkest-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Green-Darkest/gnome-shell/gnome-shell.css
themes/Flat-Remix-Green-Light-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Green-Light/gnome-shell/gnome-shell.css
themes/Flat-Remix-Grey-Dark-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Grey-Dark/gnome-shell/gnome-shell.css
themes/Flat-Remix-Grey-Darkest-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Grey-Darkest/gnome-shell/gnome-shell.css
themes/Flat-Remix-Grey-Light-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Grey-Light/gnome-shell/gnome-shell.css
themes/Flat-Remix-Magenta-Dark-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Magenta-Dark/gnome-shell/gnome-shell.css
themes/Flat-Remix-Magenta-Darkest-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Magenta-Darkest/gnome-shell/gnome-shell.css
themes/Flat-Remix-Magenta-Light-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Magenta-Light/gnome-shell/gnome-shell.css
themes/Flat-Remix-Miami-Dark-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Miami-Dark/gnome-shell/gnome-shell.css
themes/Flat-Remix-Miami-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Miami/gnome-shell/gnome-shell.css
themes/Flat-Remix-Orange-Dark-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Orange-Dark/gnome-shell/gnome-shell.css
themes/Flat-Remix-Orange-Darkest-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Orange-Darkest/gnome-shell/gnome-shell.css
themes/Flat-Remix-Orange-Light-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Orange-Light/gnome-shell/gnome-shell.css
themes/Flat-Remix-Red-Dark-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Red-Dark/gnome-shell/gnome-shell.css
themes/Flat-Remix-Red-Darkest-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Red-Darkest/gnome-shell/gnome-shell.css
themes/Flat-Remix-Red-Light-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Red-Light/gnome-shell/gnome-shell.css
themes/Flat-Remix-Teal-Dark-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Teal-Dark/gnome-shell/gnome-shell.css
themes/Flat-Remix-Teal-Darkest-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Teal-Darkest/gnome-shell/gnome-shell.css
themes/Flat-Remix-Teal-Light-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Teal-Light/gnome-shell/gnome-shell.css
themes/Flat-Remix-Violet-Dark-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Violet-Dark/gnome-shell/gnome-shell.css
themes/Flat-Remix-Violet-Darkest-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Violet-Darkest/gnome-shell/gnome-shell.css
themes/Flat-Remix-Violet-Light-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Violet-Light/gnome-shell/gnome-shell.css
themes/Flat-Remix-White-Dark-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-White-Dark/gnome-shell/gnome-shell.css
themes/Flat-Remix-White-Darkest-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-White-Darkest/gnome-shell/gnome-shell.css
themes/Flat-Remix-Yellow-Dark-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Yellow-Dark/gnome-shell/gnome-shell.css
themes/Flat-Remix-Yellow-Darkest-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Yellow-Darkest/gnome-shell/gnome-shell.css
themes/Flat-Remix-Yellow-Light-fullPanel/gnome-shell/gnome-shell.css
themes/Flat-Remix-Yellow-Light/gnome-shell/gnome-shell.css
)
rm "${RMFILES[@]}"
git add "${RMFILES[@]}"
